name: security-action
on:
  push:
    branches: [dev]
jobs:
  # API GATEWAYS BUILD AND SCAN
  DevStore-Bff-Checkout:
    name: auto package DevStore-Bff-Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: veracode CLI Download
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: | 
          cd src/api-gateways/DevStore.Bff.Checkout     
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output . --trust
          ls -l

      - name: pipeline-scan DevStore-Bff-Checkout
        id: pipeline-scan-DevStore-Bff-Checkout
        uses: veracode/Veracode-pipeline-scan-action@v1.0.16
        with:
          vid: ${{ secrets.VERACODE_ID }}
          vkey: ${{ secrets.VERACODE_KEY }}
          file: "src/api-gateways/DevStore.Bff.Checkout/veracode-auto-pack-DevStore.Bff.Checkout-dotnet.zip"
          fail_build: "false"

  # BUILDING BLOCKS BUILD AND SCAN
  DevStore-Core:
    name: auto package DevStore-Core
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: veracode CLI Download
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: | 
          cd src/building-blocks/DevStore.Core     
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output . --trust
          ls -l

  DevStore-MessageBus:
    name: auto package DevStore-MessageBus
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: veracode CLI Download
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: | 
          cd src/building-blocks/DevStore.MessageBus    
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output . --trust
          ls -l

  DevStore-WebAPI-Core:
    name: auto package DevStore-WebAPI-Core
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: veracode CLI Download
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: | 
          cd src/building-blocks/DevStore.WebAPI.Core    
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output . --trust
          ls -l

      - name: pipeline-scan DevStore-WebAPI-Core
        id: pipeline-scan-DevStore-WebAPI-Core
        uses: veracode/Veracode-pipeline-scan-action@v1.0.16
        with:
          vid: ${{ secrets.VERACODE_ID }}
          vkey: ${{ secrets.VERACODE_KEY }}
          file: "src/building-blocks/DevStore.WebAPI.Core/veracode-auto-pack-DevStore.WebAPI.Core-dotnet.zip"
          fail_build: "false"

  # SERVICES BUILD AND SCAN
  DevStore-Billing-API:
    name: auto package DevStore.Billing.API
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: veracode CLI Download
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: | 
          cd src/services/DevStore.Billing.API     
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output . --trust
          ls -l

      - name: pipeline-scan DevStore-Billing-API
        id: pipeline-scan-DevStore-Billing-API
        uses: veracode/Veracode-pipeline-scan-action@v1.0.16
        with:
          vid: ${{ secrets.VERACODE_ID }}
          vkey: ${{ secrets.VERACODE_KEY }}
          file: "src/services/DevStore.Billing.API/veracode-auto-pack-DevStore.Billing.API-dotnet.zip"
          fail_build: "false"

  DevStore-Billing-DevsPay:
    name: auto package DevStore-Billing-DevsPay
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: veracode CLI Download
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: | 
          cd src/services/DevStore.Billing.DevsPay     
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output . --trust
          ls -l

  DevStore-Catalog-API:
    name: auto package DevStore-Catalog-API
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: veracode CLI Download
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: | 
          cd src/services/DevStore.Catalog.API     
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output . --trust
          ls -l

      - name: pipeline-scan DevStore-Catalog-API
        id: pipeline-scan-DevStore-Catalog-API
        uses: veracode/Veracode-pipeline-scan-action@v1.0.16
        with:
          vid: ${{ secrets.VERACODE_ID }}
          vkey: ${{ secrets.VERACODE_KEY }}
          file: "src/services/DevStore.Customers.API/veracode-auto-pack-DevStore.Customers.API-dotnet.zip"
          fail_build: "false"

  DevStore-Customers-API:
    name: auto package DevStore-Customers-API
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: veracode CLI Download
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: | 
          cd src/services/DevStore.Customers.API    
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output . --trust
          ls -l

      - name: pipeline-scan DevStore-Customers-API
        id: pipeline-scan-DevStore-Customers-API
        uses: veracode/Veracode-pipeline-scan-action@v1.0.16
        with:
          vid: ${{ secrets.VERACODE_ID }}
          vkey: ${{ secrets.VERACODE_KEY }}
          file: "src/services/DevStore.Customers.API/veracode-auto-pack-DevStore.Customers.API-dotnet.zip"
          fail_build: "false"

  DevStore-Identity-API:
    name: auto package DevStore-Identity-API
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: veracode CLI Download
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: | 
          cd src/services/DevStore.Identity.API
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output . --trust
          ls -l

  DevStore-Orders-API:
    name: auto package DevStore-Orders-API
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: veracode CLI Download
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: | 
          cd src/services/DevStore.Orders.API  
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output . --trust
          ls -l

  DevStore-Orders-Domain:
    name: auto package DevStore-Orders-Domain
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: veracode CLI Download
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: | 
          cd src/services/DevStore.Orders.Domain 
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output . --trust
          ls -l

  DevStore-Orders-Infra:
    name: auto package DevStore-Orders-Infra
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: veracode CLI Download
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: | 
          cd src/services/DevStore.Orders.Infra 
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output . --trust
          ls -l


  DevStore-ShoppingCart-API:
    name: auto package DevStore-ShoppingCart-API
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: veracode CLI Download
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: | 
          cd src/services/DevStore.ShoppingCart.API 
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output . --trust
          ls -l
  
  # WEB BUILD AND SCAN
  DevStore-WebApp-MVC:
    name: auto package DevStore-WebApp-MVC
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: veracode CLI Download
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: | 
          cd src/web/DevStore.WebApp.MVC       
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output . --trust
          ls -l

      - name: pipeline-scan DevStore-WebApp-MVC
        id: pipeline-scan-DevStore-WebApp-MVC
        uses: veracode/Veracode-pipeline-scan-action@v1.0.16
        with:
          vid: ${{ secrets.VERACODE_ID }}
          vkey: ${{ secrets.VERACODE_KEY }}
          file: "src/web/DevStore.WebApp.MVC/veracode-auto-pack-DevStore.WebApp.MVC-dotnet.zip"
          fail_build: "false"
  
  DevStore-WebApp-Status:
    name: auto package DevStore.WebApp.Status
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: veracode CLI Download
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: | 
          cd src/web/DevStore.WebApp.Status      
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output . --trust
          ls -l